// tools/compat/render.go
//
// Renders a CompatReport into a human-readable docs/compatibility.md file.
package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

const (
	statusPass    = "pass"
	statusFail    = "fail"
	statusPartial = "partial"
)

var statusIcon = map[string]string{
	statusPass:    "✅",
	statusFail:    "❌",
	statusPartial: "⚠️",
}

// renderMarkdown writes the compatibility markdown to path.
func renderMarkdown(report CompatReport, path string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	w := func(s string, args ...interface{}) {
		_, _ = fmt.Fprintf(f, s+"\n", args...)
	}

	// ── Header ────────────────────────────────────────────────────────────────
	w("# MongoDB Compatibility Matrix")
	w("")
	w("Generated: `%s`  ", report.GeneratedAt)
	w("Salvobase version: `%s`  ", report.Version)
	w("Server URI: `%s`", report.ServerURI)
	w("")
	w("**Legend:** ✅ pass  ❌ fail  ⚠️ partial")
	w("")

	// ── Summary ───────────────────────────────────────────────────────────────
	pass, fail, partial := 0, 0, 0
	for _, r := range report.Results {
		switch r.Status {
		case statusPass:
			pass++
		case statusFail:
			fail++
		case statusPartial:
			partial++
		}
	}
	total := pass + fail + partial
	pct := 0
	if total > 0 {
		pct = (pass * 100) / total
	}
	w("## Summary")
	w("")
	w("| Metric | Value |")
	w("|--------|-------|")
	w("| Total probes | %d |", total)
	w("| Pass | %d |", pass)
	w("| Fail | %d |", fail)
	w("| Partial | %d |", partial)
	w("| Pass rate | %d%% |", pct)
	w("")

	// ── Per-category tables ───────────────────────────────────────────────────

	// Collect categories in stable order.
	catOrder := []string{
		"Commands",
		"Query Operators",
		"Update Operators",
		"Aggregation Stages",
		"Aggregation Expressions",
	}
	byCategory := make(map[string][]CompatResult)
	for _, r := range report.Results {
		byCategory[r.Category] = append(byCategory[r.Category], r)
	}

	// Also pick up any categories not in our known order.
	known := make(map[string]bool)
	for _, c := range catOrder {
		known[c] = true
	}
	var extra []string
	for cat := range byCategory {
		if !known[cat] {
			extra = append(extra, cat)
		}
	}
	sort.Strings(extra)
	allCats := append(catOrder, extra...)

	for _, cat := range allCats {
		rows, ok := byCategory[cat]
		if !ok || len(rows) == 0 {
			continue
		}

		// Category header with mini-summary.
		catPass, catFail, catPartial := 0, 0, 0
		for _, r := range rows {
			switch r.Status {
			case statusPass:
				catPass++
			case statusFail:
				catFail++
			case statusPartial:
				catPartial++
			}
		}
		w("## %s", cat)
		w("")
		w("✅ %d  ❌ %d  ⚠️ %d", catPass, catFail, catPartial)
		w("")
		w("| Feature | Status | Notes |")
		w("|---------|--------|-------|")
		for _, r := range rows {
			icon := statusIcon[r.Status]
			if icon == "" {
				icon = "?"
			}
			note := escapeMarkdown(r.Note)
			w("| `%s` | %s %s | %s |", r.Name, icon, r.Status, note)
		}
		w("")
	}

	// ── Footer ────────────────────────────────────────────────────────────────
	w("---")
	w("")
	w("*Generated by `tools/compat` — run `make compat` to refresh.*")

	return nil
}

// escapeMarkdown escapes pipe characters to avoid breaking markdown tables.
func escapeMarkdown(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	// Keep notes short — truncate at 120 chars to avoid huge table cells.
	if len(s) > 120 {
		s = s[:117] + "..."
	}
	return s
}
